-- ====================================================================
-- LEESINCOMIC.COM DATABASE DUMP (FULL 642 COMICS, 33 TEAMS)
-- Generated: 2026-09-30T23:48:57.420Z
-- Charset: utf8mb4 / Engine: InnoDB
-- Fully Compatible with phpMyAdmin, DirectAdmin, cPanel, MySQL 5.7+, MySQL 8.0+, MariaDB 10.3+
-- ====================================================================

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

-- Drop old incompatible tables first to prevent collision and schema errors
DROP TABLE IF EXISTS `chapters`;
DROP TABLE IF EXISTS `comics`;
DROP TABLE IF EXISTS `scan_teams`;
DROP TABLE IF EXISTS `teams`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `chapter_comments`;
DROP TABLE IF EXISTS `reading_history`;
DROP TABLE IF EXISTS `followed_comics`;
DROP TABLE IF EXISTS `followed_teams`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `site_settings`;
DROP TABLE IF EXISTS `system_settings`;

-- 1. Table scan_teams & teams
CREATE TABLE `scan_teams` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `avatar` TEXT NULL,
  `bio` TEXT NULL,
  `donate_info` TEXT NULL,
  `donate_qr` TEXT NULL,
  `leader_id` VARCHAR(191) NULL,
  `leader_name` VARCHAR(255) NULL,
  `total_views` BIGINT DEFAULT 0,
  `follows` INT DEFAULT 0,
  `daily_views` JSON NULL,
  `monthly_views` JSON NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_scan_team_slug` (`slug`),
  INDEX `idx_scan_team_views` (`total_views`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `teams` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `avatar` TEXT NULL,
  `bio` TEXT NULL,
  `donate_info` TEXT NULL,
  `donate_qr` TEXT NULL,
  `leader_id` VARCHAR(191) NULL,
  `leader_name` VARCHAR(255) NULL,
  `total_views` BIGINT DEFAULT 0,
  `follows` INT DEFAULT 0,
  `daily_views` JSON NULL,
  `monthly_views` JSON NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_team_slug` (`slug`),
  INDEX `idx_team_views` (`total_views`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Table users
CREATE TABLE `users` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(191) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NULL,
  `avatar` TEXT NULL,
  `role` VARCHAR(32) DEFAULT 'READER',
  `team_id` VARCHAR(191) NULL,
  `team_name` VARCHAR(255) NULL,
  `can_upload` TINYINT(1) DEFAULT 0,
  `created_at` VARCHAR(64) NULL,
  INDEX `idx_user_email` (`email`),
  INDEX `idx_user_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Table comics
CREATE TABLE `comics` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `other_names` JSON NULL,
  `cover_image` TEXT NULL,
  `banner_image` TEXT NULL,
  `authors` JSON NULL,
  `status` VARCHAR(64) DEFAULT 'Đang tiến hành',
  `genres` JSON NULL,
  `summary` LONGTEXT NULL,
  `team_id` VARCHAR(191) NULL,
  `team_name` VARCHAR(255) NULL,
  `views` BIGINT DEFAULT 0,
  `views_day` INT DEFAULT 0,
  `views_week` INT DEFAULT 0,
  `views_month` INT DEFAULT 0,
  `daily_views` BIGINT DEFAULT 0,
  `weekly_views` BIGINT DEFAULT 0,
  `monthly_views` BIGINT DEFAULT 0,
  `likes` INT DEFAULT 0,
  `follows` INT DEFAULT 0,
  `rating` FLOAT DEFAULT 5.0,
  `rating_count` INT DEFAULT 1,
  `is_hot` TINYINT(1) DEFAULT 0,
  `is_trending` TINYINT(1) DEFAULT 0,
  `is_vip_only` TINYINT(1) DEFAULT 0,
  `seo` JSON NULL,
  `seo_title` VARCHAR(255) NULL,
  `seo_desc` TEXT NULL,
  `seo_keyword` VARCHAR(255) NULL,
  `canonical_url` VARCHAR(255) NULL,
  `updated_at` VARCHAR(64) DEFAULT 'Vừa xong',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_comic_views` (`views`),
  INDEX `idx_comic_hot` (`is_hot`),
  INDEX `idx_comic_team` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Table chapters
CREATE TABLE `chapters` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `comic_id` VARCHAR(191) NOT NULL,
  `comic_title` VARCHAR(255) NULL,
  `chapter_number` FLOAT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `is_password_protected` TINYINT(1) DEFAULT 0,
  `password` VARCHAR(255) DEFAULT '',
  `scheduled_date` VARCHAR(64) DEFAULT '',
  `views` BIGINT DEFAULT 0,
  `images` LONGTEXT NOT NULL,
  `team_id` VARCHAR(191) NULL,
  `team_name` VARCHAR(255) NULL,
  `created_at` VARCHAR(64) NULL,
  INDEX `idx_chap_comic` (`comic_id`),
  INDEX `idx_chap_num` (`comic_id`, `chapter_number`),
  INDEX `idx_chap_views` (`views`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Table comments & chapter_comments
CREATE TABLE `comments` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `comic_id` VARCHAR(191) NOT NULL,
  `chapter_id` VARCHAR(191) NULL,
  `user_id` VARCHAR(191) NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `user_avatar` TEXT NULL,
  `user_role` VARCHAR(32) DEFAULT 'READER',
  `content` TEXT NOT NULL,
  `likes` INT DEFAULT 0,
  `dislikes` INT DEFAULT 0,
  `comic_title` VARCHAR(255) NULL,
  `chapter_number` FLOAT NULL,
  `created_at` VARCHAR(64) NULL,
  INDEX `idx_c_comic` (`comic_id`),
  INDEX `idx_c_chap` (`chapter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `chapter_comments` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `comic_id` VARCHAR(191) NULL,
  `comic_title` VARCHAR(255) NULL,
  `comic_slug` VARCHAR(191) NULL,
  `cover_image` TEXT NULL,
  `chapter_id` VARCHAR(191) NULL,
  `chapter_number` FLOAT NULL DEFAULT 0,
  `chapter_title` VARCHAR(255) NULL,
  `user_id` VARCHAR(191) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `user_avatar` TEXT NULL,
  `user_role` VARCHAR(50) DEFAULT 'READER',
  `content` TEXT NOT NULL,
  `likes` INT DEFAULT 0,
  `parent_id` VARCHAR(191) NULL,
  `reply_to_user_id` VARCHAR(191) NULL,
  `reply_to_user_name` VARCHAR(255) NULL,
  `ip_address` VARCHAR(45) NULL,
  `status` VARCHAR(32) DEFAULT 'VISIBLE',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_cc_comic` (`comic_id`),
  INDEX `idx_cc_chap` (`chapter_id`),
  INDEX `idx_cc_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Table reading_history
CREATE TABLE `reading_history` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `user_id` VARCHAR(191) NOT NULL,
  `comic_id` VARCHAR(191) NOT NULL,
  `chapter_id` VARCHAR(191) NOT NULL,
  `chapter_title` VARCHAR(255) NULL,
  `chapter_number` FLOAT NULL,
  `last_page` INT DEFAULT 1,
  `total_pages` INT DEFAULT 1,
  `read_at` VARCHAR(64) NULL,
  INDEX `idx_rh_user` (`user_id`),
  INDEX `idx_rh_comic` (`comic_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Table followed_comics
CREATE TABLE `followed_comics` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `user_id` VARCHAR(191) NOT NULL,
  `comic_id` VARCHAR(191) NOT NULL,
  `followed_at` VARCHAR(64) NULL,
  `notification_enabled` TINYINT(1) DEFAULT 1,
  INDEX `idx_fc_user` (`user_id`),
  INDEX `idx_fc_comic` (`comic_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Table followed_teams
CREATE TABLE `followed_teams` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `user_id` VARCHAR(191) NOT NULL,
  `team_id` VARCHAR(191) NOT NULL,
  `team_name` VARCHAR(255) NULL,
  `team_slug` VARCHAR(191) NULL,
  `team_avatar` TEXT NULL,
  `team_bio` TEXT NULL,
  `donate_info` TEXT NULL,
  `followed_at` VARCHAR(64) NULL,
  `notification_enabled` TINYINT(1) DEFAULT 1,
  INDEX `idx_ft_user` (`user_id`),
  INDEX `idx_ft_team` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Table notifications
CREATE TABLE `notifications` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `recipient_user_id` VARCHAR(191) NULL,
  `recipient_team_id` VARCHAR(191) NULL,
  `type` VARCHAR(50) NOT NULL DEFAULT 'COMMENT',
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `sender_id` VARCHAR(191) NULL,
  `sender_name` VARCHAR(255) NULL,
  `sender_avatar` TEXT NULL,
  `comic_id` VARCHAR(191) NULL,
  `comic_title` VARCHAR(255) NULL,
  `comic_slug` VARCHAR(191) NULL,
  `chapter_number` FLOAT NULL,
  `is_read` TINYINT(1) DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_notif_user` (`recipient_user_id`),
  INDEX `idx_notif_team` (`recipient_team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Table site_settings & system_settings
CREATE TABLE `site_settings` (
  `setting_key` VARCHAR(64) PRIMARY KEY,
  `setting_val` LONGTEXT,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `system_settings` (
  `setting_key` VARCHAR(100) PRIMARY KEY,
  `setting_value` LONGTEXT,
  `description` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- INSERT SCAN TEAMS (33 Teams)
-- ====================================================================
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-lessin-comic', 'Lessin Comic', 'lessin-comic', 'https://tachserver.site/cdn3/uploads/avatar/lessin-comic-1763349912.jpeg', 'Nhóm dịch Lessin Comic chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Lessin Comic qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-lessin-comic-leader', 'Trưởng Nhóm Lessin Comic', 914602, 3026, '{\"2026-09-24\":1,\"2026-09-30\":1,\"2026-10-01\":4}', '{\"2026-05\":128005,\"2026-06\":164578,\"2026-07\":192008,\"2026-08\":210294,\"2026-09\":219439,\"2026-10\":4}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-lessin-comic', 'Lessin Comic', 'lessin-comic', 'https://tachserver.site/cdn3/uploads/avatar/lessin-comic-1763349912.jpeg', 'Nhóm dịch Lessin Comic chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Lessin Comic qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-lessin-comic-leader', 'Trưởng Nhóm Lessin Comic', 914602, 3026, '{\"2026-09-24\":1,\"2026-09-30\":1,\"2026-10-01\":4}', '{\"2026-05\":128005,\"2026-06\":164578,\"2026-07\":192008,\"2026-08\":210294,\"2026-09\":219439,\"2026-10\":4}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-xi-xeo', 'Xí Xẹo', 'xi-xeo', 'https://tachserver.site/cdn3/uploads/avatar/xi-xeo-1778941070.png', 'Nhóm dịch Xí Xẹo chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Xí Xẹo qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-xi-xeo-leader', 'Trưởng Nhóm Xí Xẹo', 2152, 12, '{}', '{\"2026-05\":680,\"2026-06\":874,\"2026-07\":1020,\"2026-08\":1117,\"2026-09\":1168,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-xi-xeo', 'Xí Xẹo', 'xi-xeo', 'https://tachserver.site/cdn3/uploads/avatar/xi-xeo-1778941070.png', 'Nhóm dịch Xí Xẹo chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Xí Xẹo qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-xi-xeo-leader', 'Trưởng Nhóm Xí Xẹo', 2152, 12, '{}', '{\"2026-05\":680,\"2026-06\":874,\"2026-07\":1020,\"2026-08\":1117,\"2026-09\":1168,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-spadez', 'spadez', 'spadez', 'https://tachserver.site/cdn3/uploads/avatar/spadez-1759595819.png', 'Nhóm dịch spadez chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm spadez qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-spadez-leader', 'Trưởng Nhóm spadez', 17904, 59, '{}', '{\"2026-05\":2514,\"2026-06\":3232,\"2026-07\":3771,\"2026-08\":4130,\"2026-09\":4313,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-spadez', 'spadez', 'spadez', 'https://tachserver.site/cdn3/uploads/avatar/spadez-1759595819.png', 'Nhóm dịch spadez chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm spadez qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-spadez-leader', 'Trưởng Nhóm spadez', 17904, 59, '{}', '{\"2026-05\":2514,\"2026-06\":3232,\"2026-07\":3771,\"2026-08\":4130,\"2026-09\":4313,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-kurage-house', 'Kurage House', 'kurage-house', 'https://tachserver.site/cdn3/uploads/avatar/kurage-house-1786637129.jpg', 'Nhóm dịch Kurage House chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Kurage House qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-kurage-house-leader', 'Trưởng Nhóm Kurage House', 3368, 12, '{}', '{\"2026-05\":547,\"2026-06\":704,\"2026-07\":821,\"2026-08\":900,\"2026-09\":942,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-kurage-house', 'Kurage House', 'kurage-house', 'https://tachserver.site/cdn3/uploads/avatar/kurage-house-1786637129.jpg', 'Nhóm dịch Kurage House chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Kurage House qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-kurage-house-leader', 'Trưởng Nhóm Kurage House', 3368, 12, '{}', '{\"2026-05\":547,\"2026-06\":704,\"2026-07\":821,\"2026-08\":900,\"2026-09\":942,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tinh-da', 'Tĩnh Dạ', 'tinh-da', 'https://tachserver.site/cdn3/uploads/avatar/tinh-da-1759336856.jpeg', 'Nhóm dịch Tĩnh Dạ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tĩnh Dạ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tinh-da-leader', 'Trưởng Nhóm Tĩnh Dạ', 28172, 93, '{\"2026-09-24\":1}', '{\"2026-05\":4168,\"2026-06\":5359,\"2026-07\":6253,\"2026-08\":6848,\"2026-09\":7149,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tinh-da', 'Tĩnh Dạ', 'tinh-da', 'https://tachserver.site/cdn3/uploads/avatar/tinh-da-1759336856.jpeg', 'Nhóm dịch Tĩnh Dạ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tĩnh Dạ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tinh-da-leader', 'Trưởng Nhóm Tĩnh Dạ', 28172, 93, '{\"2026-09-24\":1}', '{\"2026-05\":4168,\"2026-06\":5359,\"2026-07\":6253,\"2026-08\":6848,\"2026-09\":7149,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-vuon-hoa-mat-troi', 'Vườn Hoa Mặt Trời', 'vuon-hoa-mat-troi', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hoa-mat-troi-1782234265.jpeg', 'Nhóm dịch Vườn Hoa Mặt Trời chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Vườn Hoa Mặt Trời qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-vuon-hoa-mat-troi-leader', 'Trưởng Nhóm Vườn Hoa Mặt Trời', 3897, 12, '{}', '{\"2026-05\":545,\"2026-06\":701,\"2026-07\":818,\"2026-08\":896,\"2026-09\":937,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-vuon-hoa-mat-troi', 'Vườn Hoa Mặt Trời', 'vuon-hoa-mat-troi', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hoa-mat-troi-1782234265.jpeg', 'Nhóm dịch Vườn Hoa Mặt Trời chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Vườn Hoa Mặt Trời qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-vuon-hoa-mat-troi-leader', 'Trưởng Nhóm Vườn Hoa Mặt Trời', 3897, 12, '{}', '{\"2026-05\":545,\"2026-06\":701,\"2026-07\":818,\"2026-08\":896,\"2026-09\":937,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-un-in-out', 'Ủn Ỉn (out)', 'un-in-out', 'https://tachserver.site/cdn3/uploads/avatar/un-in-1785720729.jpg', 'Nhóm dịch Ủn Ỉn (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Ủn Ỉn (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-un-in-out-leader', 'Trưởng Nhóm Ủn Ỉn (out)', 554, 12, '{}', '{\"2026-05\":77,\"2026-06\":99,\"2026-07\":116,\"2026-08\":127,\"2026-09\":135,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-un-in-out', 'Ủn Ỉn (out)', 'un-in-out', 'https://tachserver.site/cdn3/uploads/avatar/un-in-1785720729.jpg', 'Nhóm dịch Ủn Ỉn (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Ủn Ỉn (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-un-in-out-leader', 'Trưởng Nhóm Ủn Ỉn (out)', 554, 12, '{}', '{\"2026-05\":77,\"2026-06\":99,\"2026-07\":116,\"2026-08\":127,\"2026-09\":135,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-bi-ngan-trans', 'Bỉ Ngạn Trans', 'bi-ngan-trans', 'https://tachserver.site/cdn3/uploads/avatar/bi-ngan-trans-1760503818.jpg', 'Nhóm dịch Bỉ Ngạn Trans chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Bỉ Ngạn Trans qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-bi-ngan-trans-leader', 'Trưởng Nhóm Bỉ Ngạn Trans', 2121, 12, '{}', '{\"2026-05\":297,\"2026-06\":382,\"2026-07\":445,\"2026-08\":488,\"2026-09\":511,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-bi-ngan-trans', 'Bỉ Ngạn Trans', 'bi-ngan-trans', 'https://tachserver.site/cdn3/uploads/avatar/bi-ngan-trans-1760503818.jpg', 'Nhóm dịch Bỉ Ngạn Trans chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Bỉ Ngạn Trans qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-bi-ngan-trans-leader', 'Trưởng Nhóm Bỉ Ngạn Trans', 2121, 12, '{}', '{\"2026-05\":297,\"2026-06\":382,\"2026-07\":445,\"2026-08\":488,\"2026-09\":511,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-pinky-team', 'Pinky Team', 'pinky-team', 'https://tachserver.site/cdn3/uploads/avatar/pinky-team-1787295974.png', 'Nhóm dịch Pinky Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Pinky Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-pinky-team-leader', 'Trưởng Nhóm Pinky Team', 1392, 12, '{}', '{\"2026-05\":201,\"2026-06\":259,\"2026-07\":302,\"2026-08\":330,\"2026-09\":347,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-pinky-team', 'Pinky Team', 'pinky-team', 'https://tachserver.site/cdn3/uploads/avatar/pinky-team-1787295974.png', 'Nhóm dịch Pinky Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Pinky Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-pinky-team-leader', 'Trưởng Nhóm Pinky Team', 1392, 12, '{}', '{\"2026-05\":201,\"2026-06\":259,\"2026-07\":302,\"2026-08\":330,\"2026-09\":347,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-wyns-den-out', 'Wyn\'s Den (out)', 'wyns-den-out', 'https://tachserver.site/cdn3/uploads/avatar/Wyn-s-den-out--1778246273.jpg', 'Nhóm dịch Wyn\'s Den (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Wyn\'s Den (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-wyns-den-out-leader', 'Trưởng Nhóm Wyn\'s Den (out)', 33662, 111, '{}', '{\"2026-05\":4729,\"2026-06\":6080,\"2026-07\":7093,\"2026-08\":7769,\"2026-09\":8109,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-wyns-den-out', 'Wyn\'s Den (out)', 'wyns-den-out', 'https://tachserver.site/cdn3/uploads/avatar/Wyn-s-den-out--1778246273.jpg', 'Nhóm dịch Wyn\'s Den (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Wyn\'s Den (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-wyns-den-out-leader', 'Trưởng Nhóm Wyn\'s Den (out)', 33662, 111, '{}', '{\"2026-05\":4729,\"2026-06\":6080,\"2026-07\":7093,\"2026-08\":7769,\"2026-09\":8109,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-nguyet-ha-team', 'Nguyệt Hạ Team', 'nguyet-ha-team', 'https://tachserver.site/cdn3/uploads/avatar/nguyet-ha-team-1783615859.jpg', 'Nhóm dịch Nguyệt Hạ Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Nguyệt Hạ Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-nguyet-ha-team-leader', 'Trưởng Nhóm Nguyệt Hạ Team', 3615, 12, '{}', '{\"2026-05\":838,\"2026-06\":1078,\"2026-07\":1258,\"2026-08\":1378,\"2026-09\":1440,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-nguyet-ha-team', 'Nguyệt Hạ Team', 'nguyet-ha-team', 'https://tachserver.site/cdn3/uploads/avatar/nguyet-ha-team-1783615859.jpg', 'Nhóm dịch Nguyệt Hạ Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Nguyệt Hạ Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-nguyet-ha-team-leader', 'Trưởng Nhóm Nguyệt Hạ Team', 3615, 12, '{}', '{\"2026-05\":838,\"2026-06\":1078,\"2026-07\":1258,\"2026-08\":1378,\"2026-09\":1440,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-nora-translation-team', 'Nora Translation Team', 'nora-translation-team', 'https://tachserver.site/cdn3/uploads/avatar/nora-translation-team-1771006285.jpg', 'Nhóm dịch Nora Translation Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Nora Translation Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-nora-translation-team-leader', 'Trưởng Nhóm Nora Translation Team', 12818, 41, '{}', '{\"2026-05\":3431,\"2026-06\":4412,\"2026-07\":5147,\"2026-08\":5638,\"2026-09\":5886,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-nora-translation-team', 'Nora Translation Team', 'nora-translation-team', 'https://tachserver.site/cdn3/uploads/avatar/nora-translation-team-1771006285.jpg', 'Nhóm dịch Nora Translation Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Nora Translation Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-nora-translation-team-leader', 'Trưởng Nhóm Nora Translation Team', 12818, 41, '{}', '{\"2026-05\":3431,\"2026-06\":4412,\"2026-07\":5147,\"2026-08\":5638,\"2026-09\":5886,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-yoru-translation-team-out', 'Yoru Translation Team (out)', 'yoru-translation-team-out', 'https://tachserver.site/cdn3/uploads/avatar/yoru-translation-team-1783836172.jpg', 'Nhóm dịch Yoru Translation Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Yoru Translation Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-yoru-translation-team-out-leader', 'Trưởng Nhóm Yoru Translation Team (out)', 291, 12, '{}', '{\"2026-05\":135,\"2026-06\":174,\"2026-07\":203,\"2026-08\":222,\"2026-09\":234,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-yoru-translation-team-out', 'Yoru Translation Team (out)', 'yoru-translation-team-out', 'https://tachserver.site/cdn3/uploads/avatar/yoru-translation-team-1783836172.jpg', 'Nhóm dịch Yoru Translation Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Yoru Translation Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-yoru-translation-team-out-leader', 'Trưởng Nhóm Yoru Translation Team (out)', 291, 12, '{}', '{\"2026-05\":135,\"2026-06\":174,\"2026-07\":203,\"2026-08\":222,\"2026-09\":234,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-mua-thang-sau', 'Mưa Tháng Sáu', 'mua-thang-sau', 'https://tachserver.site/cdn3/uploads/avatar/mua-thang-sau-1786378124.png', 'Nhóm dịch Mưa Tháng Sáu chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Mưa Tháng Sáu qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-mua-thang-sau-leader', 'Trưởng Nhóm Mưa Tháng Sáu', 40140, 120, '{}', '{\"2026-05\":5620,\"2026-06\":7225,\"2026-07\":8430,\"2026-08\":9232,\"2026-09\":9636,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-mua-thang-sau', 'Mưa Tháng Sáu', 'mua-thang-sau', 'https://tachserver.site/cdn3/uploads/avatar/mua-thang-sau-1786378124.png', 'Nhóm dịch Mưa Tháng Sáu chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Mưa Tháng Sáu qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-mua-thang-sau-leader', 'Trưởng Nhóm Mưa Tháng Sáu', 40140, 120, '{}', '{\"2026-05\":5620,\"2026-06\":7225,\"2026-07\":8430,\"2026-08\":9232,\"2026-09\":9636,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tiem-banh-ngot', 'Tiệm Bánh Ngọt', 'tiem-banh-ngot', 'https://tachserver.site/cdn3/uploads/avatar/tiem-banh-ngot-1784270354.png', 'Nhóm dịch Tiệm Bánh Ngọt chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tiệm Bánh Ngọt qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tiem-banh-ngot-leader', 'Trưởng Nhóm Tiệm Bánh Ngọt', 252, 12, '{}', '{\"2026-05\":137,\"2026-06\":177,\"2026-07\":206,\"2026-08\":226,\"2026-09\":238,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tiem-banh-ngot', 'Tiệm Bánh Ngọt', 'tiem-banh-ngot', 'https://tachserver.site/cdn3/uploads/avatar/tiem-banh-ngot-1784270354.png', 'Nhóm dịch Tiệm Bánh Ngọt chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tiệm Bánh Ngọt qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tiem-banh-ngot-leader', 'Trưởng Nhóm Tiệm Bánh Ngọt', 252, 12, '{}', '{\"2026-05\":137,\"2026-06\":177,\"2026-07\":206,\"2026-08\":226,\"2026-09\":238,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-pheromone', 'Pheromone', 'pheromone', 'https://tachserver.site/cdn3/uploads/avatar/pheromone-1786463682.jpg', 'Nhóm dịch Pheromone chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Pheromone qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-pheromone-leader', 'Trưởng Nhóm Pheromone', 258774, 789, '{}', '{\"2026-05\":36613,\"2026-06\":47075,\"2026-07\":54920,\"2026-08\":60151,\"2026-09\":62769,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-pheromone', 'Pheromone', 'pheromone', 'https://tachserver.site/cdn3/uploads/avatar/pheromone-1786463682.jpg', 'Nhóm dịch Pheromone chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Pheromone qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-pheromone-leader', 'Trưởng Nhóm Pheromone', 258774, 789, '{}', '{\"2026-05\":36613,\"2026-06\":47075,\"2026-07\":54920,\"2026-08\":60151,\"2026-09\":62769,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-iris-team-out', 'Iris Team (out)', 'iris-team-out', 'https://tachserver.site/cdn3/uploads/avatar/iris-team--1766907010.jpeg', 'Nhóm dịch Iris Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Iris Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-iris-team-out-leader', 'Trưởng Nhóm Iris Team (out)', 23859, 79, '{}', '{\"2026-05\":3346,\"2026-06\":4302,\"2026-07\":5019,\"2026-08\":5497,\"2026-09\":5740,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-iris-team-out', 'Iris Team (out)', 'iris-team-out', 'https://tachserver.site/cdn3/uploads/avatar/iris-team--1766907010.jpeg', 'Nhóm dịch Iris Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Iris Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-iris-team-out-leader', 'Trưởng Nhóm Iris Team (out)', 23859, 79, '{}', '{\"2026-05\":3346,\"2026-06\":4302,\"2026-07\":5019,\"2026-08\":5497,\"2026-09\":5740,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-vuon-hat-de', 'Vườn Hạt Dẻ', 'vuon-hat-de', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hat-de-1786556819.png', 'Nhóm dịch Vườn Hạt Dẻ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Vườn Hạt Dẻ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-vuon-hat-de-leader', 'Trưởng Nhóm Vườn Hạt Dẻ', 4054, 13, '{\"2026-09-24\":1}', '{\"2026-05\":572,\"2026-06\":735,\"2026-07\":858,\"2026-08\":940,\"2026-09\":982,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-vuon-hat-de', 'Vườn Hạt Dẻ', 'vuon-hat-de', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hat-de-1786556819.png', 'Nhóm dịch Vườn Hạt Dẻ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Vườn Hạt Dẻ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-vuon-hat-de-leader', 'Trưởng Nhóm Vườn Hạt Dẻ', 4054, 13, '{\"2026-09-24\":1}', '{\"2026-05\":572,\"2026-06\":735,\"2026-07\":858,\"2026-08\":940,\"2026-09\":982,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-dau-do-out', 'Đậu Đỏ (out)', 'dau-do-out', 'https://tachserver.site/cdn3/uploads/avatar/dau-do-1759323573.png', 'Nhóm dịch Đậu Đỏ (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Đậu Đỏ (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-dau-do-out-leader', 'Trưởng Nhóm Đậu Đỏ (out)', 2305, 12, '{}', '{\"2026-05\":336,\"2026-06\":433,\"2026-07\":505,\"2026-08\":553,\"2026-09\":579,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-dau-do-out', 'Đậu Đỏ (out)', 'dau-do-out', 'https://tachserver.site/cdn3/uploads/avatar/dau-do-1759323573.png', 'Nhóm dịch Đậu Đỏ (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Đậu Đỏ (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-dau-do-out-leader', 'Trưởng Nhóm Đậu Đỏ (out)', 2305, 12, '{}', '{\"2026-05\":336,\"2026-06\":433,\"2026-07\":505,\"2026-08\":553,\"2026-09\":579,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-cuc-than-thanh-out', 'Cúc Thần Thánh (out)', 'cuc-than-thanh-out', 'https://tachserver.site/cdn3/uploads/avatar/cuc-than-thanh-1759513197.jpg', 'Nhóm dịch Cúc Thần Thánh (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Cúc Thần Thánh (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-cuc-than-thanh-out-leader', 'Trưởng Nhóm Cúc Thần Thánh (out)', 4834, 15, '{}', '{\"2026-05\":884,\"2026-06\":1136,\"2026-07\":1326,\"2026-08\":1452,\"2026-09\":1518,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-cuc-than-thanh-out', 'Cúc Thần Thánh (out)', 'cuc-than-thanh-out', 'https://tachserver.site/cdn3/uploads/avatar/cuc-than-thanh-1759513197.jpg', 'Nhóm dịch Cúc Thần Thánh (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Cúc Thần Thánh (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-cuc-than-thanh-out-leader', 'Trưởng Nhóm Cúc Thần Thánh (out)', 4834, 15, '{}', '{\"2026-05\":884,\"2026-06\":1136,\"2026-07\":1326,\"2026-08\":1452,\"2026-09\":1518,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-shortie-squad-out', 'Shortie Squad (out)', 'shortie-squad-out', 'https://tachserver.site/cdn3/uploads/avatar/shortie-squad-1759249661.png', 'Nhóm dịch Shortie Squad (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Shortie Squad (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-shortie-squad-out-leader', 'Trưởng Nhóm Shortie Squad (out)', 22955, 76, '{}', '{\"2026-05\":3214,\"2026-06\":4132,\"2026-07\":4821,\"2026-08\":5280,\"2026-09\":5513,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-shortie-squad-out', 'Shortie Squad (out)', 'shortie-squad-out', 'https://tachserver.site/cdn3/uploads/avatar/shortie-squad-1759249661.png', 'Nhóm dịch Shortie Squad (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Shortie Squad (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-shortie-squad-out-leader', 'Trưởng Nhóm Shortie Squad (out)', 22955, 76, '{}', '{\"2026-05\":3214,\"2026-06\":4132,\"2026-07\":4821,\"2026-08\":5280,\"2026-09\":5513,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-bach-duong-team', 'Bạch Dương Team', 'bach-duong-team', 'https://tachserver.site/cdn3/uploads/avatar/bach-duong-team-1759247238.png', 'Nhóm dịch Bạch Dương Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Bạch Dương Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-bach-duong-team-leader', 'Trưởng Nhóm Bạch Dương Team', 51519, 170, '{}', '{\"2026-05\":7374,\"2026-06\":9481,\"2026-07\":11062,\"2026-08\":12115,\"2026-09\":12645,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-bach-duong-team', 'Bạch Dương Team', 'bach-duong-team', 'https://tachserver.site/cdn3/uploads/avatar/bach-duong-team-1759247238.png', 'Nhóm dịch Bạch Dương Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Bạch Dương Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-bach-duong-team-leader', 'Trưởng Nhóm Bạch Dương Team', 51519, 170, '{}', '{\"2026-05\":7374,\"2026-06\":9481,\"2026-07\":11062,\"2026-08\":12115,\"2026-09\":12645,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-cuu-thap-tu', 'Cửu Thập Tứ', 'cuu-thap-tu', 'https://tachserver.site/cdn3/uploads/avatar/cuu-thap-tu-1759252992.jpg', 'Nhóm dịch Cửu Thập Tứ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Cửu Thập Tứ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-cuu-thap-tu-leader', 'Trưởng Nhóm Cửu Thập Tứ', 795, 12, '{}', '{\"2026-05\":111,\"2026-06\":143,\"2026-07\":166,\"2026-08\":182,\"2026-09\":193,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-cuu-thap-tu', 'Cửu Thập Tứ', 'cuu-thap-tu', 'https://tachserver.site/cdn3/uploads/avatar/cuu-thap-tu-1759252992.jpg', 'Nhóm dịch Cửu Thập Tứ chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Cửu Thập Tứ qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-cuu-thap-tu-leader', 'Trưởng Nhóm Cửu Thập Tứ', 795, 12, '{}', '{\"2026-05\":111,\"2026-06\":143,\"2026-07\":166,\"2026-08\":182,\"2026-09\":193,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-la-muse-team', 'Là Muse Team', 'la-muse-team', 'https://tachserver.site/cdn3/uploads/avatar/la-muse-team-1784781951.jpg', 'Nhóm dịch Là Muse Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Là Muse Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-la-muse-team-leader', 'Trưởng Nhóm Là Muse Team', 17042, 53, '{}', '{\"2026-05\":2423,\"2026-06\":3116,\"2026-07\":3635,\"2026-08\":3981,\"2026-09\":4158,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-la-muse-team', 'Là Muse Team', 'la-muse-team', 'https://tachserver.site/cdn3/uploads/avatar/la-muse-team-1784781951.jpg', 'Nhóm dịch Là Muse Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Là Muse Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-la-muse-team-leader', 'Trưởng Nhóm Là Muse Team', 17042, 53, '{}', '{\"2026-05\":2423,\"2026-06\":3116,\"2026-07\":3635,\"2026-08\":3981,\"2026-09\":4158,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-louisiana-translation-out', 'Louisiana Translation (out)', 'louisiana-translation-out', 'https://tachserver.site/cdn3/uploads/avatar/louisiana-translation--1771820371.png', 'Nhóm dịch Louisiana Translation (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Louisiana Translation (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-louisiana-translation-out-leader', 'Trưởng Nhóm Louisiana Translation (out)', 1140, 12, '{}', '{\"2026-05\":193,\"2026-06\":249,\"2026-07\":290,\"2026-08\":318,\"2026-09\":334,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-louisiana-translation-out', 'Louisiana Translation (out)', 'louisiana-translation-out', 'https://tachserver.site/cdn3/uploads/avatar/louisiana-translation--1771820371.png', 'Nhóm dịch Louisiana Translation (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Louisiana Translation (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-louisiana-translation-out-leader', 'Trưởng Nhóm Louisiana Translation (out)', 1140, 12, '{}', '{\"2026-05\":193,\"2026-06\":249,\"2026-07\":290,\"2026-08\":318,\"2026-09\":334,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tieu-ho-diep-out', 'Tiểu Hồ Điệp (out)', 'tieu-ho-diep-out', 'https://tachserver.site/cdn3/uploads/avatar/tieu-ho-diep-1776757717.jpg', 'Nhóm dịch Tiểu Hồ Điệp (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tiểu Hồ Điệp (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tieu-ho-diep-out-leader', 'Trưởng Nhóm Tiểu Hồ Điệp (out)', 9761, 32, '{}', '{\"2026-05\":1366,\"2026-06\":1756,\"2026-07\":2049,\"2026-08\":2245,\"2026-09\":2345,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tieu-ho-diep-out', 'Tiểu Hồ Điệp (out)', 'tieu-ho-diep-out', 'https://tachserver.site/cdn3/uploads/avatar/tieu-ho-diep-1776757717.jpg', 'Nhóm dịch Tiểu Hồ Điệp (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tiểu Hồ Điệp (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tieu-ho-diep-out-leader', 'Trưởng Nhóm Tiểu Hồ Điệp (out)', 9761, 32, '{}', '{\"2026-05\":1366,\"2026-06\":1756,\"2026-07\":2049,\"2026-08\":2245,\"2026-09\":2345,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-lavibit-windroom-gl', 'Lavibit Windroom GL', 'lavibit-windroom-gl', 'https://tachserver.site/cdn3/uploads/avatar/lavibit-Windroom-gl-1784437408.png', 'Nhóm dịch Lavibit Windroom GL chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Lavibit Windroom GL qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-lavibit-windroom-gl-leader', 'Trưởng Nhóm Lavibit Windroom GL', 259416, 840, '{\"2026-09-24\":1,\"2026-10-01\":1}', '{\"2026-05\":36351,\"2026-06\":46738,\"2026-07\":54527,\"2026-08\":59720,\"2026-09\":62320,\"2026-10\":1}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-lavibit-windroom-gl', 'Lavibit Windroom GL', 'lavibit-windroom-gl', 'https://tachserver.site/cdn3/uploads/avatar/lavibit-Windroom-gl-1784437408.png', 'Nhóm dịch Lavibit Windroom GL chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Lavibit Windroom GL qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-lavibit-windroom-gl-leader', 'Trưởng Nhóm Lavibit Windroom GL', 259416, 840, '{\"2026-09-24\":1,\"2026-10-01\":1}', '{\"2026-05\":36351,\"2026-06\":46738,\"2026-07\":54527,\"2026-08\":59720,\"2026-09\":62320,\"2026-10\":1}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-water-team-out', 'Water Team (out)', 'water-team-out', 'https://tachserver.site/cdn3/uploads/avatar/water-team-1781314786.jpg', 'Nhóm dịch Water Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Water Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-water-team-out-leader', 'Trưởng Nhóm Water Team (out)', 1702, 12, '{}', '{\"2026-05\":238,\"2026-06\":306,\"2026-07\":357,\"2026-08\":391,\"2026-09\":411,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-water-team-out', 'Water Team (out)', 'water-team-out', 'https://tachserver.site/cdn3/uploads/avatar/water-team-1781314786.jpg', 'Nhóm dịch Water Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Water Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-water-team-out-leader', 'Trưởng Nhóm Water Team (out)', 1702, 12, '{}', '{\"2026-05\":238,\"2026-06\":306,\"2026-07\":357,\"2026-08\":391,\"2026-09\":411,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-meo-beo-team-out', 'Mèo Béo Team (out)', 'meo-beo-team-out', 'https://tachserver.site/cdn3/uploads/avatar/meo-beo-team-1785347705.jpeg', 'Nhóm dịch Mèo Béo Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Mèo Béo Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-meo-beo-team-out-leader', 'Trưởng Nhóm Mèo Béo Team (out)', 657, 12, '{}', '{\"2026-05\":167,\"2026-06\":215,\"2026-07\":251,\"2026-08\":275,\"2026-09\":288,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-meo-beo-team-out', 'Mèo Béo Team (out)', 'meo-beo-team-out', 'https://tachserver.site/cdn3/uploads/avatar/meo-beo-team-1785347705.jpeg', 'Nhóm dịch Mèo Béo Team (out) chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Mèo Béo Team (out) qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-meo-beo-team-out-leader', 'Trưởng Nhóm Mèo Béo Team (out)', 657, 12, '{}', '{\"2026-05\":167,\"2026-06\":215,\"2026-07\":251,\"2026-08\":275,\"2026-09\":288,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-sipj-team', 'Sipj Team', 'sipj-team', 'https://tachserver.site/cdn3/uploads/avatar/sipj-team-1786207130.jpeg', 'Nhóm dịch Sipj Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Sipj Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-sipj-team-leader', 'Trưởng Nhóm Sipj Team', 311, 12, '{}', '{\"2026-05\":77,\"2026-06\":99,\"2026-07\":116,\"2026-08\":127,\"2026-09\":134,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-sipj-team', 'Sipj Team', 'sipj-team', 'https://tachserver.site/cdn3/uploads/avatar/sipj-team-1786207130.jpeg', 'Nhóm dịch Sipj Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Sipj Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-sipj-team-leader', 'Trưởng Nhóm Sipj Team', 311, 12, '{}', '{\"2026-05\":77,\"2026-06\":99,\"2026-07\":116,\"2026-08\":127,\"2026-09\":134,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tu-ky-cung-e', 'Tự Kỷ Cùng É', 'tu-ky-cung-e', 'https://tachserver.site/cdn3/uploads/avatar/tu-ky-cung-e-1788876449.png', 'Nhóm dịch Tự Kỷ Cùng É chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tự Kỷ Cùng É qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tu-ky-cung-e-leader', 'Trưởng Nhóm Tự Kỷ Cùng É', 2465, 12, '{}', '{\"2026-05\":913,\"2026-06\":1174,\"2026-07\":1370,\"2026-08\":1501,\"2026-09\":1569,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-tu-ky-cung-e', 'Tự Kỷ Cùng É', 'tu-ky-cung-e', 'https://tachserver.site/cdn3/uploads/avatar/tu-ky-cung-e-1788876449.png', 'Nhóm dịch Tự Kỷ Cùng É chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Tự Kỷ Cùng É qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-tu-ky-cung-e-leader', 'Trưởng Nhóm Tự Kỷ Cùng É', 2465, 12, '{}', '{\"2026-05\":913,\"2026-06\":1174,\"2026-07\":1370,\"2026-08\":1501,\"2026-09\":1569,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-linguabridge-team', 'Linguabridge Team', 'linguabridge-team', 'https://tachserver.site/cdn3/uploads/avatar/linguabridge-team-1789202578.png', 'Nhóm dịch Linguabridge Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Linguabridge Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-linguabridge-team-leader', 'Trưởng Nhóm Linguabridge Team', 9, 12, '{}', '{\"2026-05\":7,\"2026-06\":9,\"2026-07\":10,\"2026-08\":11,\"2026-09\":13,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-linguabridge-team', 'Linguabridge Team', 'linguabridge-team', 'https://tachserver.site/cdn3/uploads/avatar/linguabridge-team-1789202578.png', 'Nhóm dịch Linguabridge Team chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm Linguabridge Team qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-linguabridge-team-leader', 'Trưởng Nhóm Linguabridge Team', 9, 12, '{}', '{\"2026-05\":7,\"2026-06\":9,\"2026-07\":10,\"2026-08\":11,\"2026-09\":13,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `scan_teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-j97', 'j97', 'j97', 'https://tachserver.site/cdn3/uploads/avatar/j97-1777609339.jpg', 'Nhóm dịch j97 chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm j97 qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-j97-leader', 'Trưởng Nhóm j97', 61125, 12, '{}', '{\"2026-05\":8557,\"2026-06\":11002,\"2026-07\":12836,\"2026-08\":14058,\"2026-09\":14672,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);
INSERT INTO `teams` (`id`, `name`, `slug`, `avatar`, `bio`, `donate_info`, `donate_qr`, `leader_id`, `leader_name`, `total_views`, `follows`, `daily_views`, `monthly_views`) VALUES ('team-j97', 'j97', 'j97', 'https://tachserver.site/cdn3/uploads/avatar/j97-1777609339.jpg', 'Nhóm dịch j97 chính thức trên Leesin Comic (leesincomic.com). Chuyên chuyển ngữ và phát hành truyện tranh độc quyền chất lượng cao.', 'Ủng hộ nhóm j97 qua STK ngân hàng hoặc MoMo để nhóm có kinh phí dịch truyện tiếp nhé!', NULL, 'user-j97-leader', 'Trưởng Nhóm j97', 61125, 12, '{}', '{\"2026-05\":8557,\"2026-06\":11002,\"2026-07\":12836,\"2026-08\":14058,\"2026-09\":14672,\"2026-10\":0}') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `total_views`=VALUES(`total_views`);

-- ====================================================================
-- INSERT USERS (35 Users)
-- ====================================================================
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-admin', 'Admin Leesin Comic', 'admin', 'admin@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', 'ADMIN', 'team-leesin', 'Leesin Scans', 1, '2026-01-01') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-lessin-comic-leader', 'Trưởng Nhóm Lessin Comic', 'lessin-comic', 'lessin-comic@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/lessin-comic-1763349912.jpeg', 'TEAM_LEADER', 'team-lessin-comic', 'Lessin Comic', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-xi-xeo-leader', 'Trưởng Nhóm Xí Xẹo', 'xi-xeo', 'xi-xeo@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/xi-xeo-1778941070.png', 'TEAM_LEADER', 'team-xi-xeo', 'Xí Xẹo', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-spadez-leader', 'Trưởng Nhóm spadez', 'spadez', 'spadez@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/spadez-1759595819.png', 'TEAM_LEADER', 'team-spadez', 'spadez', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-kurage-house-leader', 'Trưởng Nhóm Kurage House', 'kurage-house', 'kurage-house@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/kurage-house-1786637129.jpg', 'TEAM_LEADER', 'team-kurage-house', 'Kurage House', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-tinh-da-leader', 'Trưởng Nhóm Tĩnh Dạ', 'tinh-da', 'tinh-da@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/tinh-da-1759336856.jpeg', 'TEAM_LEADER', 'team-tinh-da', 'Tĩnh Dạ', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-vuon-hoa-mat-troi-leader', 'Trưởng Nhóm Vườn Hoa Mặt Trời', 'vuon-hoa-mat-troi', 'vuon-hoa-mat-troi@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hoa-mat-troi-1782234265.jpeg', 'TEAM_LEADER', 'team-vuon-hoa-mat-troi', 'Vườn Hoa Mặt Trời', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-un-in-out-leader', 'Trưởng Nhóm Ủn Ỉn (out)', 'un-in-out', 'un-in-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/un-in-1785720729.jpg', 'TEAM_LEADER', 'team-un-in-out', 'Ủn Ỉn (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-bi-ngan-trans-leader', 'Trưởng Nhóm Bỉ Ngạn Trans', 'bi-ngan-trans', 'bi-ngan-trans@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/bi-ngan-trans-1760503818.jpg', 'TEAM_LEADER', 'team-bi-ngan-trans', 'Bỉ Ngạn Trans', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-pinky-team-leader', 'Trưởng Nhóm Pinky Team', 'pinky-team', 'pinky-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/pinky-team-1787295974.png', 'TEAM_LEADER', 'team-pinky-team', 'Pinky Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-wyns-den-out-leader', 'Trưởng Nhóm Wyn\'s Den (out)', 'wyns-den-out', 'wyns-den-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/Wyn-s-den-out--1778246273.jpg', 'TEAM_LEADER', 'team-wyns-den-out', 'Wyn\'s Den (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-nguyet-ha-team-leader', 'Trưởng Nhóm Nguyệt Hạ Team', 'nguyet-ha-team', 'nguyet-ha-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/nguyet-ha-team-1783615859.jpg', 'TEAM_LEADER', 'team-nguyet-ha-team', 'Nguyệt Hạ Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-nora-translation-team-leader', 'Trưởng Nhóm Nora Translation Team', 'nora-translation-team', 'nora-translation-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/nora-translation-team-1771006285.jpg', 'TEAM_LEADER', 'team-nora-translation-team', 'Nora Translation Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-yoru-translation-team-out-leader', 'Trưởng Nhóm Yoru Translation Team (out)', 'yoru-translation-team-out', 'yoru-translation-team-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/yoru-translation-team-1783836172.jpg', 'TEAM_LEADER', 'team-yoru-translation-team-out', 'Yoru Translation Team (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-mua-thang-sau-leader', 'Trưởng Nhóm Mưa Tháng Sáu', 'mua-thang-sau', 'mua-thang-sau@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/mua-thang-sau-1786378124.png', 'TEAM_LEADER', 'team-mua-thang-sau', 'Mưa Tháng Sáu', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-tiem-banh-ngot-leader', 'Trưởng Nhóm Tiệm Bánh Ngọt', 'tiem-banh-ngot', 'tiem-banh-ngot@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/tiem-banh-ngot-1784270354.png', 'TEAM_LEADER', 'team-tiem-banh-ngot', 'Tiệm Bánh Ngọt', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-pheromone-leader', 'Trưởng Nhóm Pheromone', 'pheromone', 'pheromone@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/pheromone-1786463682.jpg', 'TEAM_LEADER', 'team-pheromone', 'Pheromone', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-iris-team-out-leader', 'Trưởng Nhóm Iris Team (out)', 'iris-team-out', 'iris-team-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/iris-team--1766907010.jpeg', 'TEAM_LEADER', 'team-iris-team-out', 'Iris Team (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-vuon-hat-de-leader', 'Trưởng Nhóm Vườn Hạt Dẻ', 'vuon-hat-de', 'vuon-hat-de@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/vuon-hat-de-1786556819.png', 'TEAM_LEADER', 'team-vuon-hat-de', 'Vườn Hạt Dẻ', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-dau-do-out-leader', 'Trưởng Nhóm Đậu Đỏ (out)', 'dau-do-out', 'dau-do-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/dau-do-1759323573.png', 'TEAM_LEADER', 'team-dau-do-out', 'Đậu Đỏ (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-cuc-than-thanh-out-leader', 'Trưởng Nhóm Cúc Thần Thánh (out)', 'cuc-than-thanh-out', 'cuc-than-thanh-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/cuc-than-thanh-1759513197.jpg', 'TEAM_LEADER', 'team-cuc-than-thanh-out', 'Cúc Thần Thánh (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-shortie-squad-out-leader', 'Trưởng Nhóm Shortie Squad (out)', 'shortie-squad-out', 'shortie-squad-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/shortie-squad-1759249661.png', 'TEAM_LEADER', 'team-shortie-squad-out', 'Shortie Squad (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-bach-duong-team-leader', 'Trưởng Nhóm Bạch Dương Team', 'bach-duong-team', 'bach-duong-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/bach-duong-team-1759247238.png', 'TEAM_LEADER', 'team-bach-duong-team', 'Bạch Dương Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-cuu-thap-tu-leader', 'Trưởng Nhóm Cửu Thập Tứ', 'cuu-thap-tu', 'cuu-thap-tu@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/cuu-thap-tu-1759252992.jpg', 'TEAM_LEADER', 'team-cuu-thap-tu', 'Cửu Thập Tứ', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-la-muse-team-leader', 'Trưởng Nhóm Là Muse Team', 'la-muse-team', 'la-muse-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/la-muse-team-1784781951.jpg', 'TEAM_LEADER', 'team-la-muse-team', 'Là Muse Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-louisiana-translation-out-leader', 'Trưởng Nhóm Louisiana Translation (out)', 'louisiana-translation-out', 'louisiana-translation-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/louisiana-translation--1771820371.png', 'TEAM_LEADER', 'team-louisiana-translation-out', 'Louisiana Translation (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-tieu-ho-diep-out-leader', 'Trưởng Nhóm Tiểu Hồ Điệp (out)', 'tieu-ho-diep-out', 'tieu-ho-diep-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/tieu-ho-diep-1776757717.jpg', 'TEAM_LEADER', 'team-tieu-ho-diep-out', 'Tiểu Hồ Điệp (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-lavibit-windroom-gl-leader', 'Trưởng Nhóm Lavibit Windroom GL', 'lavibit-windroom-gl', 'lavibit-windroom-gl@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/lavibit-Windroom-gl-1784437408.png', 'TEAM_LEADER', 'team-lavibit-windroom-gl', 'Lavibit Windroom GL', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-water-team-out-leader', 'Trưởng Nhóm Water Team (out)', 'water-team-out', 'water-team-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/water-team-1781314786.jpg', 'TEAM_LEADER', 'team-water-team-out', 'Water Team (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-meo-beo-team-out-leader', 'Trưởng Nhóm Mèo Béo Team (out)', 'meo-beo-team-out', 'meo-beo-team-out@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/meo-beo-team-1785347705.jpeg', 'TEAM_LEADER', 'team-meo-beo-team-out', 'Mèo Béo Team (out)', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-sipj-team-leader', 'Trưởng Nhóm Sipj Team', 'sipj-team', 'sipj-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/sipj-team-1786207130.jpeg', 'TEAM_LEADER', 'team-sipj-team', 'Sipj Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-tu-ky-cung-e-leader', 'Trưởng Nhóm Tự Kỷ Cùng É', 'tu-ky-cung-e', 'tu-ky-cung-e@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/tu-ky-cung-e-1788876449.png', 'TEAM_LEADER', 'team-tu-ky-cung-e', 'Tự Kỷ Cùng É', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-linguabridge-team-leader', 'Trưởng Nhóm Linguabridge Team', 'linguabridge-team', 'linguabridge-team@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/linguabridge-team-1789202578.png', 'TEAM_LEADER', 'team-linguabridge-team', 'Linguabridge Team', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-j97-leader', 'Trưởng Nhóm j97', 'j97', 'j97@leesincomic.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://tachserver.site/cdn3/uploads/avatar/j97-1777609339.jpg', 'TEAM_LEADER', 'team-j97', 'j97', 1, '2026-01-15') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password_hash`, `avatar`, `role`, `team_id`, `team_name`, `can_upload`, `created_at`) VALUES ('user-reader-vip', 'Minh Thư (Độc Giả)', 'reader', 'reader@gmail.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80', 'READER', NULL, NULL, 0, '2026-06-01') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);

-- ====================================================================
-- DEFAULT SITE SETTINGS
-- ====================================================================
REPLACE INTO `system_settings` (`setting_key`, `setting_value`, `description`) VALUES
('site_name', 'Leesin Comic', 'Tên website chính thức'),
('site_domain', 'https://leesincomic.com', 'Tên miền chính thức'),
('cdn_endpoint', 'https://tachserver.site/upload.php', 'Server CDN lưu ảnh'),
('watermark_text', 'Leesin Comic - leesincomic.com', 'Bản quyền'),
('watermark_opacity', '0.45', 'Độ mờ bản quyền'),
('seo_auto_sitemap', 'true', 'Tự động tạo sitemap');

COMMIT;
SET FOREIGN_KEY_CHECKS=1;
